name = "food-vs-battle"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "FOODVS_COUNTER"
id = "564c17ec21c8406f863538d7b7c55663"

